#ifndef DIMENSIONS_H_INCLUDED
#define DIMENSIONS_H_INCLUDED
//POUR PC LYCEE: 1200*800
#define XFENETRE 1800
#define YFENETRE 950

#define NBRE_CASES_X 70
#define NBRE_CASES_Y 40

#define NBRE_ANIM_MAXIMAL 60
#endif // DIMENSIONS_H_INCLUDED
